### ISSUE TITLE
wrong declarations are generated

### ISSUE THREAD

**Issue by budarin** [skovhus/css-modules-flow-types#12]
Hi!

I used to SSModules for my project
```js
import css from './index.css';
```

Here is sample index.css:
```css
@value animationTime: 220ms;
@value menuAnimation: 220ms ease-in-out;

.layout {
    position: relative;
}

.layoutHeader {
    align-items: center;
    position: fixed;
    width: 100%;
    height: var(--headerHeight);
    top: 0;
    background-color: var(--header-color);
    box-shadow: 0 0 4px rgba(0, 0, 0, 0.14), 0 4px 8px rgba(0, 0, 0, 0.28);
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    overflow: hidden;
    color: #fff;
    user-select: none;
    transition: background-color animationTime ease-in-out;
    z-index: var(--pageHeaderZIndex);
}

.menuIcon {
    fill: #fff;
    width: 48px;
    height: 48px;
    margin: 4px;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    transition: opacity animationTime ease-in-out;
}

.menuIcon:hover,
.menuIcon:focus {
    opacity: 1;
    border: 1px solid #fff;
}

.title {
    flex: 1;
    margin-right: 56px;
    color: #fff;
    font-weight: normal;
    font-size: 20px;
    margin-left: 10px;
    align-self: center;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}

.layoutContent {
    margin-top: var(--headerHeight);
    padding: 10px;
    overflow-x: hidden;
    overflow-y: auto;
    -webkit-overflow-scrolling: touch;
}

.appSideMenu {
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    position: fixed;
    pointer-events: none;
    overflow: hidden;
    user-select: none;
    z-index: var(--leftMenuZIndex);
}

:global body.showMenu :local .appSideMenu {
    pointer-events: auto;
}

.appSideMenu:before {
    content: '';
    height: 100%;
    width: 100%;
    background: #000;
    opacity: 0;
    display: block;
    position: absolute;

    will-change: opacity;
    transition: opacity 220ms ease-in-out;
}

:global body.showMenu :local .appSideMenu:before {
    opacity: 0.5;
}

.menu {
    width: 304px;
    height: 100%;
    background: #fff;
    box-shadow: 0 0 11px 0 rgba(0, 0, 0, 0.4);
    cursor: default;
    overflow-y: auto;
    -webkit-overflow-scrolling: touch;
    transform: translateX(-110%);

    will-change: transform;
    transition: transform menuAnimation;
    user-select: none;
}

:global body.showMenu :local .menu {
    transform: translateX(0);
}

.menuHeader {
    /*background: url('../../assets/side-nav-bg@2x.jpg');*/
    background-color: var(--header-color);
    background-size: cover;
    height: 150px;
    color: #fff;
    border-bottom: 1px solid #ddd;
    padding: 10px;
    user-select: none;
    position: relative;
}

.menuHeaderTitle {
    font-size: 1.5rem;
    line-height: 1;
    color: #fff;
    position: absolute;
    bottom: 10px;
    left: 10px;
    height: 1.5rem;
    font-weight: 500;
}

.menuBody {
    padding: 10px;
}
```
package generates flow declaration as
```js
// @flow
/* This file is automatically generated by css-modules-flow-types */
declare module.exports: {|
  +'animationTime': string;
  +'appSideMenu': string;
  +'layout': string;
  +'layoutContent': string;
  +'layoutHeader': string;
  +'menu': string;
  +'menuAnimation': string;
  +'menuBody': string;
  +'menuHeader': string;
  +'menuHeaderTitle': string;
  +'menuIcon': string;
  +'title': string;
|};
```
which is not right when I use it in my code like this
```js
    <div className={css.layoutContent}>Sample content</div>
```
here is the correct declaration
```js
// @flow
/* This file is automatically generated by css-modules-flow-types */
declare module.exports: {|
    +animationTime: string,
    +appSideMenu: string,
    +layout: string,
    +layoutContent: string,
    +layoutHeader: string,
    +menu: string,
    +menuAnimation: string,
    +menuBody: string,
    +menuHeader: string,
    +menuHeaderTitle: string,
    +menuIcon: string,
    +title: string,
|};
```
here are my iisues:
- have ability to configure generated file extention (it's not always suitable to operate with .flow extention)
- not to place classnames into comas - CSSModules require right javascript identifiers for classnames
- replace ; with ,
- ability to configure to have hanging comma after last item
